// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP7PcTAI21C4xPbMbc-OaiO5uodpVWWKw',
    appId: '1:305214322068:web:1dc43f91c7fdab1730cb81',
    messagingSenderId: '305214322068',
    projectId: 'student-manager-69bd8',
    authDomain: 'student-manager-69bd8.firebaseapp.com',
    storageBucket: 'student-manager-69bd8.firebasestorage.app',
    measurementId: 'G-10KQQCBDZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-3fuzzpKrZNc48I70EIuHQkvyglZgEA',
    appId: '1:305214322068:android:2be9eb2a22ab0d2e30cb81',
    messagingSenderId: '305214322068',
    projectId: 'student-manager-69bd8',
    storageBucket: 'student-manager-69bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLfuRi0nHcMMDRIMU684a3VJ7tGbIyws',
    appId: '1:305214322068:ios:574326f1f1799eb830cb81',
    messagingSenderId: '305214322068',
    projectId: 'student-manager-69bd8',
    storageBucket: 'student-manager-69bd8.firebasestorage.app',
    iosBundleId: 'com.example.ahmedAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWLfuRi0nHcMMDRIMU684a3VJ7tGbIyws',
    appId: '1:305214322068:ios:574326f1f1799eb830cb81',
    messagingSenderId: '305214322068',
    projectId: 'student-manager-69bd8',
    storageBucket: 'student-manager-69bd8.firebasestorage.app',
    iosBundleId: 'com.example.ahmedAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP7PcTAI21C4xPbMbc-OaiO5uodpVWWKw',
    appId: '1:305214322068:web:2148a917ae1982e230cb81',
    messagingSenderId: '305214322068',
    projectId: 'student-manager-69bd8',
    authDomain: 'student-manager-69bd8.firebaseapp.com',
    storageBucket: 'student-manager-69bd8.firebasestorage.app',
    measurementId: 'G-N1SB2BKP6J',
  );
}
